- core/src/main/java/org/openstack4j/model/heat/builder/StackCreateBuilder.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackCreate.java
- core/src/main/java/org/openstack4j/openstack/heat/utils/Environment.java
- core/src/main/java/org/openstack4j/openstack/heat/utils/Template.java
- core/src/main/java/org/openstack4j/openstack/heat/utils/TemplateUtils.java
- pom.xml
It is the first version of the template and environment file parsing. The code won't impact old functionalities.
> First version of the template and environment file parsing 

- core/src/main/java/org/openstack4j/api/heat/StackService.java
- core/src/main/java/org/openstack4j/model/heat/builder/StackUpdateBuilder.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackUpdate.java
- core/src/main/java/org/openstack4j/openstack/heat/internal/StackServiceImpl.java
1. StackUpdate supports Environment file and Template file with "get_file"
2. Add findStack API.
> Orchestration API update

- core/src/main/java/org/openstack4j/openstack/heat/utils/Template.java
- core/src/main/java/org/openstack4j/openstack/heat/utils/TemplateUtils.java
Add the Nested template support to resolve issue 183.
> Heat: Nested templates (Files & Env) support for a Stack #183

- core/src/main/java/org/openstack4j/model/network/AllowedAddressPair.java
- core/src/main/java/org/openstack4j/model/network/Port.java
- core/src/main/java/org/openstack4j/model/network/builder/PortBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronAllowedAddressPair.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java
Added AllowedAddressPair to NeutronPort implementation
> Added AllowedAddressPair to NeutronPort

- CHANGELOG.md
- connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/HttpCommand.java
- core-test/src/main/java/org/openstack4j/api/AbstractTest.java
- core-test/src/main/java/org/openstack4j/api/identity/KeystoneTests.java
- core-test/src/main/java/org/openstack4j/api/metering/AlarmTests.java
- core-test/src/main/resources/all.xml
- core-test/src/main/resources/metering/alarms.json
- core/src/main/java/org/openstack4j/api/heat/ResourcesService.java
- core/src/main/java/org/openstack4j/api/heat/TemplateService.java
- core/src/main/java/org/openstack4j/api/telemetry/AlarmService.java
- core/src/main/java/org/openstack4j/api/telemetry/MeterService.java
- core/src/main/java/org/openstack4j/api/telemetry/TelemetryService.java
- core/src/main/java/org/openstack4j/model/heat/builder/StackCreateBuilder.java
- core/src/main/java/org/openstack4j/model/telemetry/Alarm.java
- core/src/main/java/org/openstack4j/model/telemetry/Sample.java
- core/src/main/java/org/openstack4j/openstack/common/ListEntity.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackCreate.java
- core/src/main/java/org/openstack4j/openstack/heat/internal/ResourcesServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/heat/internal/TemplateServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
- core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerAlarm.java
- core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerSample.java
- core/src/main/java/org/openstack4j/openstack/telemetry/internal/AlarmServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/telemetry/internal/MeterServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/telemetry/internal/TelemetryServiceImpl.java
Added AlarmService implementation, putSamples(), and files parameter in stack create
> Added AlarmService implementation, putSamples(), and files parameter in stack create

- core/src/main/java/org/openstack4j/model/network/builder/NetworkBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronNetwork.java
> allow admin to build a shared network 

- core/src/main/java/org/openstack4j/core/transport/HttpRequest.java
- core/src/main/java/org/openstack4j/openstack/image/internal/ImageServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java
Add the function to update the http query parameters for which only has one value not a list.
Like when using query parameter "marker" to query the image list, the "marker" should be updated to use the last image id from the response for next request, not appending the value.
> Add the function to update the query parameters

- core/src/main/java/org/openstack4j/api/sahara/ClusterService.java
- core/src/main/java/org/openstack4j/core/transport/functions/ParseActionResponseFromJsonMap.java
- core/src/main/java/org/openstack4j/openstack/sahara/internal/ClusterServiceImpl.java
Regarding to the issue #245.
Please see if this modification to handle Sahara's JSON fault response is OK or not.
It is in the ParseActionResponseFromJsonMap.java.
BTW, I also change the return type of some sahara APIs to ActionResponse.
> Handle Sahara JSON fault response

- core/src/main/java/org/openstack4j/api/Builders.java
- core/src/main/java/org/openstack4j/api/telemetry/AlarmService.java
- core/src/main/java/org/openstack4j/model/telemetry/Alarm.java
- core/src/main/java/org/openstack4j/model/telemetry/builder/AlarmBuilder.java
- core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerAlarm.java
- core/src/main/java/org/openstack4j/openstack/telemetry/internal/AlarmServiceImpl.java
Added create and delete ceilometer alarms functionality.
Few files are a little modified. One new file is introduced.
> Added create and delete ceilometer alarms functionality

- core/src/main/java/org/openstack4j/model/sahara/Cluster.java
- core/src/main/java/org/openstack4j/model/sahara/Image.java
- core/src/main/java/org/openstack4j/openstack/sahara/domain/SaharaCluster.java
Just change the return type of Cluster.getStatus() from string into enum type.
> Improve Sahara Image and Cluster Status deserialization

- core/src/main/java/org/openstack4j/api/client/IOSClientBuilder.java
- core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java
- core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneAuth.java
Added some code to the V3 Auth builder so it can consume a trust when authenticating against Keystone
> Add ability to consume trust on authentication

- core/src/main/java/org/openstack4j/api/networking/ext/LbPoolService.java
- core/src/main/java/org/openstack4j/model/network/ext/LbPoolStats.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronLbPoolStats.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/ext/LbPoolServiceImpl.java
> support to stats lbpool

- core/src/main/java/org/openstack4j/model/storage/block/VolumeSnapshot.java
- core/src/main/java/org/openstack4j/model/storage/block/builder/VolumeSnapshotBuilder.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java
> Issue #334 add support for metadata in volume snapshot

- connectors/http-connector/src/main/java/org/openstack4j/connectors/http/HttpCommand.java
- connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpCommand.java
- core-test/src/main/java/org/openstack4j/api/AbstractTest.java
- core-test/src/main/java/org/openstack4j/api/storage/VolumeSnapshotTests.java
- core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java
- core-test/src/main/resources/storage/volumes.json
- core-test/src/main/resources/storage/volumes_filtered.json
- core-test/src/main/resources/storage/volumesnapshots.json
- core-test/src/main/resources/storage/volumesnapshots_filtered.json
- core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java
- core/src/main/java/org/openstack4j/api/storage/BlockVolumeSnapshotService.java
- core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeSnapshotServiceImpl.java
> Add support for filter when listing volumes and volume snapshots

- core-test/src/main/java/org/openstack4j/api/network/FirewallTests.java
- core-test/src/main/resources/network/firewall.json
- core-test/src/main/resources/network/firewalls.json
- core/src/main/java/org/openstack4j/api/Builders.java
- core/src/main/java/org/openstack4j/api/networking/NetworkingService.java
- core/src/main/java/org/openstack4j/api/networking/ext/FirewallAsService.java
- core/src/main/java/org/openstack4j/api/networking/ext/FirewallService.java
- core/src/main/java/org/openstack4j/model/network/ext/Firewall.java
- core/src/main/java/org/openstack4j/model/network/ext/FirewallUpdate.java
- core/src/main/java/org/openstack4j/model/network/ext/builder/FirewallBuilder.java
- core/src/main/java/org/openstack4j/model/network/ext/builder/FirewallUpdateBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewall.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewallUpdate.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/NetworkingServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/ext/FirewallAsServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/ext/FirewallServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Added API for `Network (Neutron) Firewall As A Service (FwaaS)`..
--> Added few tests for now. Will enhance the tests in the future.
--> `TODO`: To add `FirewallPolicyService` & `FirewallRuleService` APIs..
Please verify!
> Added API for Network (Neutron) Firewall As A Service (FwaaS)..

- connectors/jersey2-jdk16/src/main/java/org/openstack4j/connectors/jersey2/ClientFactory.java
- core/src/main/java/org/openstack4j/model/telemetry/Alarm.java
- core/src/main/java/org/openstack4j/model/telemetry/builder/AlarmBuilder.java
- core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerAlarm.java
> Add combination type alarm

- core-test/src/main/java/org/openstack4j/api/network/FirewallTests.java
- core-test/src/main/resources/network/firewallupdate.json
1) Added Create & Update Firewall Tests..
2) Substituted System.outs with Loggers..
> (FwaaS) : Firewall Tests

- core/src/main/java/org/openstack4j/core/transport/functions/ParseActionResponseFromJsonMap.java
- core/src/main/java/org/openstack4j/openstack/compute/functions/ToActionResponseFunction.java
--> Addressing issue #365
--> Added 'computeFault' key error propagation when parsing response from OpenStack.
> Added 'computeFault' key error propagation.

- core/src/main/java/org/openstack4j/model/compute/builder/BlockDeviceMappingBuilder.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaBlockDeviceMappingCreate.java
> support for creating blockdevicemapping with snapshotid and volumeid

- core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java
- core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneAuth.java
This seems to cover issue https://github.com/gondor/openstack4j/issues/366. There is only 1 place that uses this constructor so I think we can modify the existing one. Let me know what you think.
> Add scope when authenticating with an auth token

- core-test/src/main/java/org/openstack4j/api/AbstractTest.java
- core-test/src/main/java/org/openstack4j/api/compute/FloatingIPTests.java
- core-test/src/main/resources/compute/floatingips.json
- core/src/main/java/org/openstack4j/openstack/compute/functions/ToActionResponseFunction.java
> Fix issue #373 connection leak when using HttpClient

- core-test/src/main/java/org/openstack4j/api/SkipTest.java
- core-test/src/main/java/org/openstack4j/api/SkipTestListener.java
- core-test/src/main/resources/all.xml
Sample:
@Test
@SkipTest(connector = "Http URL Connector", issue = 999, description = "a description")
public void f() {...}
> Add an annotation to easily skip tests for one or more connectors

- core/src/main/java/org/openstack4j/model/image/ContainerFormat.java
Added docker container format for those who are creating glance images from docker - https://github.com/gondor/openstack4j/issues/430
> Added docker container format

- core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/ExtendAction.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/ResetStatusAction.java
- core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
extend (extending volume size to new size)
reset_status (reseting volume state to new state)
> New commands for blockVolume

- core/src/main/java/org/openstack4j/model/compute/builder/ServerCreateBuilder.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaServerCreate.java
> Add capability to modify ConfigDrive value

- core/src/main/java/org/openstack4j/model/storage/object/SwiftObject.java
- core/src/main/java/org/openstack4j/openstack/storage/object/domain/SwiftObjectImpl.java
Hello,
I provided a fix to handle subdirectories under a directory in Swift.
Kindly review & merge my pull request.
Thanks & regards,
Subhobrata
> [Fix for Issue ##485] bug fix for handling subDirectories under a directory

- core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java
- core/src/main/java/org/openstack4j/model/storage/block/Volume.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java
Fix for issue https://github.com/gondor/openstack4j/issues/454
> Add Volume 'tenantId' attribute support

- core-test/src/main/java/org/openstack4j/api/AbstractTest.java
- core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneTests.java
- core-test/src/main/resources/identity.v3/authv3_authorizationerror.json
- core-test/src/main/resources/identity.v3/usersv3_list.json
- core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneAuth.java
- core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
This PR fixes #521. Comes with test.
What do you think @gondor, @dhague ?
> reAuthenticate NPE fix #521

- core-test/src/main/java/org/openstack4j/api/AbstractTest.java
- core-test/src/main/java/org/openstack4j/api/identity/KeystoneAuthenticationTests.java
- core-test/src/main/resources/identity/authv3_authorizationerror.json
- core-test/src/main/resources/identity/authv3_project.json
- core/src/main/java/org/openstack4j/openstack/identity/domain/KeystoneAuth.java
- core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
This closes #521 on our v3_collaboration branch. Comes with test.
What do you think @gondor, @dhague ?
> reAuthentication NPE fix

- core/src/main/java/org/openstack4j/model/network/AllowedAddressPair.java
- core/src/main/java/org/openstack4j/model/network/builder/PortBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronAllowedAddressPair.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java
> Added MAC address to allowe address pair

- core-integration-test/src/test/groovy/org/openstack4j/api/identity/AbstractSpec.groovy
- core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneRoleServiceSpec.groovy
- core-integration-test/src/test/resources/tapes/roleService_all_tape.yaml
- core-test/src/main/java/org/openstack4j/api/identity/KeystoneRoleServiceTests.java
- core-test/src/main/resources/identity/roles_get_byId.json
- core-test/src/main/resources/identity/roles_update.json
- core/src/main/java/org/openstack4j/api/identity/RoleService.java
- core/src/main/java/org/openstack4j/openstack/identity/internal/RoleServiceImpl.java
Brings the V3 Role Service covering CRUD and role assignment operations as described in #544. Comes with tests.
What do you think @gondor, @dhague ?
> identity v3 role service with tests

- core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneRegionServiceSpec.groovy
- core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneServiceEndpointServiceSpec.groovy
- core-integration-test/src/test/resources/tapes/regionService_all_tape.yaml
- core-test/src/main/java/org/openstack4j/api/identity/KeystoneRegionServiceTest.java
- core-test/src/main/java/org/openstack4j/api/identity/KeystoneServiceEndpointServiceTest.java
- core-test/src/main/resources/identity/regions_get_byId.json
- core-test/src/main/resources/identity/regions_update_response.json
- core/src/main/java/org/openstack4j/api/Builders.java
- core/src/main/java/org/openstack4j/api/identity/IdentityService.java
- core/src/main/java/org/openstack4j/api/identity/RegionService.java
- core/src/main/java/org/openstack4j/core/transport/ClientConstants.java
- core/src/main/java/org/openstack4j/model/identity/Region.java
- core/src/main/java/org/openstack4j/model/identity/builder/RegionBuilder.java
- core/src/main/java/org/openstack4j/openstack/identity/domain/KeystoneRegion.java
- core/src/main/java/org/openstack4j/openstack/identity/internal/IdentityServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/identity/internal/RegionServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Closes #541.
Could you take a look @gondor, @dhague ?
> identity v3 region service

- core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/UpdateReadOnlyFlagAction.java
- core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
This is implementation of enhancement issue #618
> Add update readonly flag support

- core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageObjectServiceImpl.java
see: http://developer.openstack.org/api-ref-objectstorage-v1.html
> the successfull response state of updateMetadata is 202 instead of 204

- core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneCredentialServiceSpec.groovy
- core-integration-test/src/test/resources/tapes/identity.v3/credentialService_all_tape.yaml
- core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneCredentialServiceTests.java
- core-test/src/main/resources/identity/v3/credentials_update_response.json
- core/src/main/java/org/openstack4j/api/Builders.java
- core/src/main/java/org/openstack4j/api/identity/v3/CredentialService.java
- core/src/main/java/org/openstack4j/api/identity/v3/IdentityService.java
- core/src/main/java/org/openstack4j/core/transport/ClientConstants.java
- core/src/main/java/org/openstack4j/model/identity/v3/Credential.java
- core/src/main/java/org/openstack4j/model/identity/v3/builder/CredentialBuilder.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneCredential.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/internal/CredentialServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/internal/IdentityServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Hi @gondor, @dhague,
The Identity V3 Credential Service completes the Identity V3 API.
> identity v3 credential service

- .travis.yml
- pom.xml
@gondor, @dhague:  As discussed in #661 upgrading to jdk 8 should solve the problem.
> upgrade to java 1.8

- core/src/main/java/org/openstack4j/openstack/storage/object/functions/ParseObjectFunction.java
> NPE if there is no Content-Length in headers for HEAD responce #643

- core/src/main/java/org/openstack4j/model/compute/SecurityGroup.java
- core/src/main/java/org/openstack4j/model/compute/Server.java
- core/src/main/java/org/openstack4j/model/compute/ServerCreate.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaSecurityGroup.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaServer.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaServerCreate.java
Reference to 
https://github.com/gondor/openstack4j/issues/633
> Added security group property to Nova Server

- core/src/main/java/org/openstack4j/core/transport/ClientConstants.java
> Incorrect tenant path

- core/src/main/java/org/openstack4j/openstack/common/DLPayloadEntity.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
public static long copy(InputStream from,
OutputStream to)
throws IOException
Copies all bytes from the input stream to the output stream. **Does not close or flush either stream**.
> Closing input stream, ref#622

- core/src/main/java/org/openstack4j/openstack/common/DLPayloadEntity.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
binding for BlockQuotaSetService was missing
> Add binding for BlockQuotaSetService

- core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneRoleServiceTests.java
- core-test/src/main/resources/identity/v3/roles_assignment_list.json
- core/src/main/java/org/openstack4j/api/identity/v3/RoleService.java
- core/src/main/java/org/openstack4j/model/identity/v3/RoleAssignment.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneRoleAssignment.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/internal/RoleServiceImpl.java
> Fix #733 : add role assignment list api

- core/src/main/java/org/openstack4j/openstack/manila/internal/SchedulerStatsServiceImpl.java
> Fix URL for manila back-end storage pools

- core-test/src/main/java/org/openstack4j/api/compute/ext/InstanceActionsTests.java
- core-test/src/main/resources/compute/ext/instance_action.json
- core-test/src/main/resources/compute/ext/instance_actions.json
- core/src/main/java/org/openstack4j/api/compute/ServerService.java
- core/src/main/java/org/openstack4j/api/compute/ext/InstanceActionsService.java
- core/src/main/java/org/openstack4j/model/compute/InstanceAction.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaInstanceAction.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ServerServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ext/InstanceActionsServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Since i managed to screw up #715, this is the second try.
> Implementation for the compute API extension os-instance-actions

- core/src/main/java/org/openstack4j/api/heat/StackService.java
- core/src/main/java/org/openstack4j/model/heat/Stack.java
- core/src/main/java/org/openstack4j/model/heat/builder/StackCreateBuilder.java
- core/src/main/java/org/openstack4j/model/heat/builder/StackUpdateBuilder.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStack.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackCreate.java
- core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackUpdate.java
- core/src/main/java/org/openstack4j/openstack/heat/internal/StackServiceImpl.java
* allow stack updates and creates to specify tags
* get stack returns tags
* filter stack list by query params
> add stack tag capabilities

- core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneUserServiceTests.java
- core-test/src/main/resources/identity/v3/user_changeUserPassword_fail.json
- core/src/main/java/org/openstack4j/api/identity/v3/UserService.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/internal/UserServiceImpl.java
Add missing method "changePassword" for UserService in Identity V3 
Issue  #797
> Add missing method for user service

- core-test/src/main/java/org/openstack4j/api/compute/FlavorTests.java
- core-test/src/main/resources/compute/flavor.json
- core-test/src/main/resources/compute/flavor_create.json
- core/src/main/java/org/openstack4j/api/compute/FlavorService.java
- core/src/main/java/org/openstack4j/model/compute/builder/FlavorBuilder.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaFlavor.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/FlavorServiceImpl.java
- Ephemeral support
- isPublic bug fix
- Flavor ID get
- Related test cases
This change is contributed by Yin Zhang, Qin An(@biogerm)
> Flavor Ephemeral support

- core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneAuth.java
> KeystoneAuth does not have a default constructor #838

- core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneAuth.java
> make some classes implement the Serializable interface

- core/src/main/java/org/openstack4j/model/network/NetFloatingIP.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronFloatingIP.java
> add missing propety: status

- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronLbPoolV2.java
@JerryShi this should fix the issue - let me know if it doesn't.
@vinodborole take a look please
> Fix #856 - add @JsonProperty to NeutronLbPoolV2 sessionPersistance

- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronLbPoolV2Update.java
Addressing #856 - sorry for the delay @auhlig @JerryShi @vinodborole
> add missing @JsonProperty in NeutronLbPoolV2Update

- core-test/src/main/java/org/openstack4j/api/compute/ServiceTests.java
- core-test/src/main/resources/compute/services.json
- core/src/main/java/org/openstack4j/api/compute/ComputeService.java
- core/src/main/java/org/openstack4j/api/compute/ext/ServicesService.java
- core/src/main/java/org/openstack4j/model/compute/ext/Service.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/ext/ExtService.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ComputeServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ServicesServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Api implementation for nova service-list. Test included.
> Add api for nova service list

- core/src/main/java/org/openstack4j/model/network/builder/RouterBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronRouter.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/RouterServiceImpl.java
> Issue 903 remove last route

- CONTRIBUTING.md
- core-test/README.md
Since users asked where the unit tests are and how they work.
Also updated `Currently we support a minimum version of Java 6.` to `.. Java 7.`
Are you okay with the changes @vinodborole, @gondor?
> added unit test readme

- core-test/src/main/java/org/openstack4j/api/network/SecurityGroupTests.java
- core-test/src/main/resources/network/security_group.json
- core/src/main/java/org/openstack4j/api/Builders.java
- core/src/main/java/org/openstack4j/api/networking/SecurityGroupService.java
- core/src/main/java/org/openstack4j/model/network/SecurityGroupUpdate.java
- core/src/main/java/org/openstack4j/model/network/builder/NetSecurityGroupUpdateBuilder.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSecurityGroupUpdate.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnetUpdate.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/SecurityGroupServiceImpl.java
Implement missed implementation about security group update API and write test case https://github.com/ContainX/openstack4j/issues/973. And also fix https://github.com/ContainX/openstack4j/pull/953 syntax problem.
> Implement Security Group Update API & Support Enable DHCP

- core-test/src/main/java/org/openstack4j/api/network/PortTests.java
- core-test/src/main/resources/network/port_external.json
- core-test/src/main/resources/network/ports_external.json
- core/src/main/java/org/openstack4j/api/networking/PortService.java
- core/src/main/java/org/openstack4j/openstack/common/ListEntity.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPortCreate.java
- core/src/main/java/org/openstack4j/openstack/networking/internal/PortServiceImpl.java
> Allow Port Creation in Bulk

- core/src/main/java/org/openstack4j/model/compute/builder/BlockDeviceMappingBuilder.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaBlockDeviceMappingCreate.java
- disk_bus
- device_type
Refers to [Link](https://docs.openstack.org/developer/nova/block_device_mapping.html#block-device-mapping-v2)
> Add additional properties of block device mapping api v2

- README.md
- connectors/http-connector/pom.xml
- connectors/httpclient/pom.xml
- connectors/jersey2/pom.xml
- connectors/okhttp/pom.xml
- connectors/pom.xml
- connectors/resteasy/pom.xml
- core-integration-test/it-httpclient/pom.xml
- core-integration-test/it-jersey2/pom.xml
- core-integration-test/it-okhttp/pom.xml
- core-integration-test/it-resteasy/pom.xml
- core-integration-test/pom.xml
- core-test/pom.xml
- core/pom.xml
- distribution/pom.xml
- pom.xml
Will create a draft for a new release later. OK @gondor, @vinodborole?
> 3.0.4 release

- core-test/src/main/java/org/openstack4j/api/compute/HostAggregateTests.java
- core-test/src/main/resources/compute/aggregate_create.json
- core-test/src/main/resources/compute/aggregates.json
- core/src/main/java/org/openstack4j/api/compute/HostService.java
- core/src/main/java/org/openstack4j/api/compute/ext/HypervisorService.java
- core/src/main/java/org/openstack4j/api/compute/ext/ServicesService.java
- core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java
- core/src/main/java/org/openstack4j/model/compute/HostAggregate.java
- core/src/main/java/org/openstack4j/model/compute/HostResource.java
- core/src/main/java/org/openstack4j/model/compute/ext/Hypervisor.java
- core/src/main/java/org/openstack4j/model/compute/ext/Service.java
- core/src/main/java/org/openstack4j/model/network/Network.java
- core/src/main/java/org/openstack4j/model/network/Router.java
- core/src/main/java/org/openstack4j/model/network/builder/RouterBuilder.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaHostAggregate.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaHostAggregateCreate.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/NovaHostResource.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/ext/ExtHypervisor.java
- core/src/main/java/org/openstack4j/openstack/compute/domain/ext/ExtService.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/HostAggregateServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/HostServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ServicesServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/compute/internal/ext/HypervisorServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronNetwork.java
- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronRouter.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/AttachAction.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/ForceDetachAction.java
- core/src/main/java/org/openstack4j/openstack/storage/block/domain/ForceDetachConnector.java
- core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
Cherry picking from #932. Could you take a look @vinodborole?
> cherry-picking #932

- core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java
change @JsonProperty("name") for name & change @JsonProperty("description") for description;
for #1019
> Fix cinder volume snapshot

- core/src/main/java/org/openstack4j/model/magnum/Bay.java
- core/src/main/java/org/openstack4j/model/magnum/BayBuilder.java
- core/src/main/java/org/openstack4j/openstack/magnum/MagnumBay.java
Some fields were missing in Magnum bay model. This check-in adds those missing fields.
> Added missing fields in Magnum bay

- core-test/src/main/java/org/openstack4j/api/workflow/ActionDefinitionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkbookDefinitionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkflowDefinitionTest.java
- core-test/src/main/resources/workflow/action_def.json
- core-test/src/main/resources/workflow/action_def_create.json
- core-test/src/main/resources/workflow/action_defs.json
- core-test/src/main/resources/workflow/new_action.yaml
- core-test/src/main/resources/workflow/new_wb.yaml
- core-test/src/main/resources/workflow/wb_def.json
- core-test/src/main/resources/workflow/wb_def_create.json
- core-test/src/main/resources/workflow/wb_defs.json
- core/src/main/java/org/openstack4j/api/OSClient.java
- core/src/main/java/org/openstack4j/api/workflow/ActionDefinitionService.java
- core/src/main/java/org/openstack4j/api/workflow/WorkbookDefinitionService.java
- core/src/main/java/org/openstack4j/api/workflow/WorkflowDefinitionService.java
- core/src/main/java/org/openstack4j/model/workflow/builder/WorkbookDefinitionBuilder.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
- core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralWorkbookDefinition.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/ActionDefinitionServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/WorkbookDefinitionServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/WorkflowDefinitionServiceImpl.java
Added two more endpoints for Mistral:
* Action definitions
* Workbook definitions
> Mistral: implement endpoints for action definitions and workbook definitions

- core-test/src/main/java/org/openstack4j/api/workflow/ActionExecutionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/TaskExecutionTest.java
- core-test/src/main/resources/workflow/action_exec.json
- core-test/src/main/resources/workflow/action_exec_create.json
- core-test/src/main/resources/workflow/action_execs.json
- core-test/src/main/resources/workflow/task_exec.json
- core-test/src/main/resources/workflow/task_execs.json
- core/src/main/java/org/openstack4j/api/workflow/ActionExecutionService.java
- core/src/main/java/org/openstack4j/api/workflow/TaskExecutionService.java
- core/src/main/java/org/openstack4j/model/workflow/ActionExecution.java
- core/src/main/java/org/openstack4j/model/workflow/Execution.java
- core/src/main/java/org/openstack4j/model/workflow/TaskExecution.java
- core/src/main/java/org/openstack4j/model/workflow/builder/ActionExecutionBuilder.java
- core/src/main/java/org/openstack4j/model/workflow/builder/ExecutionBuilder.java
- core/src/main/java/org/openstack4j/model/workflow/builder/TaskExecutionBuilder.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
- core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralActionExecution.java
- core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralTaskExecution.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/ActionExecutionServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/TaskExecutionServiceImpl.java
* Added all needed entities to implement Mistral task execution endpoint
> Mistral: add task and action execution endpoints

- core-test/src/main/java/org/openstack4j/api/workflow/ActionDefinitionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/ActionExecutionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/CronTriggerTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/TaskExecutionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkbookDefinitionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkflowDefinitionTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkflowEnvironmentTest.java
- core-test/src/main/java/org/openstack4j/api/workflow/WorkflowExecutionTest.java
- core-test/src/main/resources/workflow/cron_trigger.json
- core-test/src/main/resources/workflow/cron_trigger_create.json
- core-test/src/main/resources/workflow/cron_triggers.json
- core-test/src/main/resources/workflow/wf_env.json
- core-test/src/main/resources/workflow/wf_env_create.json
- core-test/src/main/resources/workflow/wf_envs.json
- core/src/main/java/org/openstack4j/api/workflow/CronTriggerService.java
- core/src/main/java/org/openstack4j/api/workflow/WorkflowEnvironmentService.java
- core/src/main/java/org/openstack4j/model/workflow/CronTrigger.java
- core/src/main/java/org/openstack4j/model/workflow/WorkflowEnvironment.java
- core/src/main/java/org/openstack4j/model/workflow/builder/CronTriggerBuilder.java
- core/src/main/java/org/openstack4j/model/workflow/builder/WorkflowEnvironmentBuilder.java
- core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
- core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralCronTrigger.java
- core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralWorkflowEnvironment.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/ActionExecutionServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/CronTriggerServiceImpl.java
- core/src/main/java/org/openstack4j/openstack/workflow/internal/WorkflowEnvironmentServiceImpl.java
* Added all needed entities for workflow environment endpoint
* Added all needed entities for cron trigger endpoint
* Other minor fixes
> Mistral: add workflow environment and cron trigger endpoint

- core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneAuthenticationTests.java
- core-test/src/main/resources/identity/v3/authv3_token_unscoped.json
- core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java
- core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneAuth.java
- core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
> fix unscoped token authentication

- core/src/main/java/org/openstack4j/model/compute/builder/BlockDeviceMappingBuilder.java
> Update javadoc for BlockDeviceMappingBuilder

- core-test/src/main/java/org/openstack4j/openstack/common/ServiceTypeTest.java
- core/src/main/java/org/openstack4j/api/types/ServiceType.java
Fix method forName to return correct type when attribute name contains version number like "volumev3"
> Fix in ServiceTypeEnum

- core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronLbPoolV2Update.java
https://github.com/ContainX/openstack4j/issues/1091
> Fix octavia pool update session_persistence with value "null"

- core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnetUpdate.java
Fix for issue #979: Disable Gateway problem
> Fix for issue #979: Disable Gateway problem
