ContainX/openstack4j

core/src/main/java/org/openstack4j/api/image/ImageService.java, core/src/main/java/org/openstack4j/openstack/image/internal/ImageServiceImpl.java
Allow to get all images without setting the "limit" parameter.
It looks that the openstack has default PAGE_SIZE for the api request.
The /images/details cannot return all, in my environement, only 25.
=>  Allow to get all images without setting the "limit" parameter.

core/pom.xml, src/main/resources/features.xml
This patch is related with issue #214
It addresses an issue with default provider mechanism used in openstack4j-core with FallbackLoggerFactorySupplier not working in OSGi.
This mechanism do work now both in OSGi and in "normal" java environments.
FallbackLoggerFactorySupplier will be used in case no LoggerFactorySupplier provider is available.
=> Mark resolution of LoggerFactorySupplier as optional in OSGi.

core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageContainerServiceImpl.java, core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageObjectServiceImpl.java
Documentation lists format=plain as default so the Json Parser errors out without specifically setting it to json
=> Add format=json parameter to Swift GETs for container list and object list

core/src/main/java/org/openstack4j/model/identity/v3/TokenV3.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/AccessWrapper.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneTokenV3.java
I needed the user information, specifically user_id for my workflow using the V3 APIs.  This is a little dangerous since I moved the Domain specific classes out of the Project specific classes since Domains apply to Projects and Users so anyone that has imported them will need to re-import.
=> Pull in user info from V3 Authentication

connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpCommand.java
Using payloads and the Swift API in OpenStack4j was erroring out at the Jackson level since it could not serialize InputStreams to JSON.  I've pulled in code from the http-connector to handle InputStreams similarly in the okhttp-connector.
=> Use code from http-connector to fix issues with Swift (Object Store) put

core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewallPolicy.java
1) Now exposing NeutronFirewallRules (removed previous JsonIgnore).
2) There seems to be some problem with `Lists.newArrayList()` while
fetching Rules for a policy.. replaced with `new
ArrayList<NeutronFirewallRule>()`.
=> Exposing Firewall Rules for a Firewall Policy.

core-test/src/main/java/org/openstack4j/api/network/firewalls/FirewallPolicyTests.java, core-test/src/main/resources/network/firewalls/firewallpolicyrule.json, core/src/main/java/org/openstack4j/model/network/ext/FirewallPolicy.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/AbstractNeutronFirewallPolicy.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewallPolicyRule.java, core/src/main/java/org/openstack4j/openstack/networking/internal/ext/FirewallPolicyServiceImpl.java
1) Separated NeutronFirewallPolicy by creating parent
AbstractNeutronFirewallPolicy class which is extended by
NeutronFirewallPolicy & NeutronFirewalPolicyRule classes.
--> Prior has `@JsonRootName("firewall_policy")` attribute whereas the
later doesn't have (which is used by `rule_insert/rule_remove` calls -
which doesn't require JsonRootName - `firewall_policy`).
2) Fixed and added `firewallpolicyrule` test cases to add/remove rules
from a policy.
3) Removed null checks for insertRuleInPolicy call for `type` and
`insertAfterOrBeforeRuleId` fields.
4) Added `firewall_list` field in AbstractNeutronFirewallPolicy as this
extra field is returned by OpenStack after `add/remove rule` calls.
5) User can now invoke `insertFirewallRuleInPolicy` with null parameters.
```
FirewallPolicy ruleAdded …
```
=> Changes in NeutronFirewallPolicy.

core/src/main/java/org/openstack4j/openstack/networking/domain/ext/AbstractNeutronFirewallPolicy.java
--> Added `@JsonIgnore` back to `getNeutronFirewallRules()` to ignore the field while creating a `FirewallPolicy`..
=> Added `@JsonIgnore` back to `getNeutronFirewallRules()`.

core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewall.java
Added `@JsonIgnore` on `getPolicy()` in `NeutronFirewall`, as it was adding unwanted `policy` json field while making a `POST/Create` request to OpenStack. This solves the issue.
=> Added @JsonIgnore on getPolicy() in NeutronFirewall while creating Firewall.

core/src/main/java/org/openstack4j/openstack/identity/domain/v3/AccessWrapper.java, core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java
The patch submitted in this pull requests fixes an issue I discovered with openstack4j when used in a multi-regional OpenStack deployment.
More specifically, the code in its current state does not include the region specified via OSClient.useRegion() when matching endpoints from a  Keystone V3 service catalog (I'm not sure if the same issue exists when using Keystone version 2). 
The proposed patch makes sure that the DefaultEndpointURLResolver selects a service endpoint from the right region (if a region has been specified in the URLResolverParams).
=> endpoint resolution for Keystone V3 catalog services now includes region

core/src/main/java/org/openstack4j/openstack/OSFactory.java
Attempting to use ``OSFactory.clientFromAccess(client.getAccess())`` won't work with a V3 ``OSClient``.
The result is something similar to 
Exception in thread "main" java.lang.ClassCastException: org.openstack4j.openstack.identity.domain.v3.AccessWrapper cannot be cast to     
org.openstack4j.openstack.identity.domain.KeystoneAccess
at org.openstack4j.openstack.OSFactory.clientFromAccess(OSFactory.java:33)
The reason being that ``OSFactory.clientFromAccess(..)`` casts its ``Access`` object to ``KeystoneAccess`` which won't work if a V3 ``OSClient`` is used, since it uses an ``AccessWrapper`` implementation of ``Access``, rather than ``KeystoneAccess``. However, since, the code never seems to make use of ``KeystoneAccess`` it appears to be possible to simply skip the case and have the …
=> Cannot use OSFactory.clientFromAccess(..) for v3 OSClients

core/src/main/java/org/openstack4j/api/client/IOSClientBuilder.java, core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java, core/src/main/java/org/openstack4j/openstack/identity/domain/Auth.java, core/src/main/java/org/openstack4j/openstack/identity/domain/RaxApiKeyCredentials.java, core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
Rackspace supports API-key based authentication mechanism documented at
http://docs.rackspace.com/files/api/v1/cf-devguide/content/Retrieving_Auth_Token.html
and http://docs.rackspace.com/openstack-extensions/auth/RAX-KSKEY-admin-devguide/content/RackExt-0001.html.
We can use API key instead of password + tenantName with this mechanism.
This is useful especially when we want to improve security using multi-factor
authentication because password-based authentication fails if
multi-factor authentication is enabled.
We can use this extension with this code:
```java
client = OSFactory.builder()
.endpoint("https://identity.api.rackspacecloud.com/v2.0")
.credentials("myuser", "mayapikey")
.raxApiKey(true)
.authenticate()
client.objectStorage().objects().list("mycontainer")
```
I implemented it …
=> Add support for RAX API key authentication extension

core/src/main/java/org/openstack4j/api/storage/ObjectStorageObjectService.java, core/src/main/java/org/openstack4j/model/storage/object/options/ObjectDeleteOptions.java, core/src/main/java/org/openstack4j/model/storage/object/options/ObjectPutOptions.java, core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java, core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageObjectServiceImpl.java
This change adds primitive support for large objects of Swift.
Large objects are documented at http://docs.openstack.org/developer/swift/api/large_objects.html.
For example, with JRuby, we can use the additional APIs as following:
```ruby
require 'json'
import "java.io.ByteArrayInputStream"
import "org.openstack4j.openstack.OSFactory"
import "org.openstack4j.model.storage.object.options.ObjectLocation"
import "org.openstack4j.model.storage.object.options.ObjectPutOptions"
import "org.openstack4j.model.storage.object.options.ObjectDeleteOptions"
import "org.openstack4j.model.common.Payloads"
client = OSFactory.builder()...authenticate()
data1 = "segment1" * (1024 * 1024 * 5)
data2 = "segment2" * (1024 * 1024 * 5)
etag1 = client.objectStorage().objects().put(
"mycontainer", "segment1", …
```
=> Add query parameters to delete and put options for large objects

.travis.yml, core/src/main/java/org/openstack4j/model/common/DLPayload.java, core/src/main/java/org/openstack4j/openstack/common/DLPayloadEntity.java, core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java, core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageObjectServiceImpl.java
Issue: https://github.com/gondor/openstack4j/issues/444
The user’s OSClient object becomes out of scope during reauthentication because authenticateV3 does not update the OSClient object. Instead it returns a new OSClient object which is never passed back to the user during reauthentication. The user is left with the out of scope OSClient object and that OSClient's access is outdated. This becomes very problematic in multi-threaded applications.
OSAuthenticator.authenticateV2 handles it properly.
Issue: https://github.com/gondor/openstack4j/issues/446
Currently, if getting an object is not successful, the user does not
know whether the GET was successful or not.  For example, if the result
is a 404, then reading from the InputStream will result in the stream
containing the message saying …
=> Fix OSAuthenticator. authenticateV3 (Fixes #444, #446)

core/src/main/java/org/openstack4j/openstack/heat/utils/Template.java
Hi,
I change the name of the template push to the files map. In fact if the name is relative, the mapping between the master template and the sub template doesn't match because the name isn't found in the map because it became an absolute name.
Bests regards.
=> Correction nested template

core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
Fix for issue: https://github.com/gondor/openstack4j/issues/459
If the client tries to reauthenticate more than once from an expired
token, after the first time, all future reauthentications will fail
because of NPE.
Steps to reproduce:
Let client reauthenticate more than once.
Proposed solution:
Provide the endpoint and credentials to the access object during
reauthentication.
Author: Sajid Nasir
Date: 9/22/2015
Affected files:
OSAuthenticator.java,
=> Fixing NPE from v3 reauths (Fixes #459)

core/src/main/java/org/openstack4j/api/Apis.java, core/src/main/java/org/openstack4j/core/transport/internal/HttpExecutor.java, core/src/main/java/org/openstack4j/openstack/logging/LoggerFactory.java
`ServiceLoader.load(Class)` relies on context class loader by default. As openstack4j does not provide any, this effectively delegates the responsibility for resetting context classloaders with each call that looks up extensions (which is a process that should be encapsulated) to the client.
I am using openstack4j in environment where context classloaders can not load necessary classes so without this fix, I have to wrap the calls into:
```java
final Thread thread = Thread.currentThread();
final ClassLoader oldLoader = thread.getContextClassLoader();
thread.setContextClassLoader(getClass().getClassLoader());
try {
// Now use the convenient openstack4j DSL
} finally {
thread.setContextClassLoader(oldLoader);
}
```
I suggest to rely on whatever classloader loaded openstack4j classes. If …
=> Kill context classloader

core/src/main/java/org/openstack4j/core/transport/internal/HttpExecutor.java
When openstack4j fails to load `HttpExecutorService` implementation it throws an exception while initializing class (static field `HttpExecutor.INSTANCE` -> constructor -> `throw`). The real cause is wrapped in unhelpful exception:
```
java.lang.NoClassDefFoundError: Could not initialize class org.openstack4j.core.transport.internal.HttpExecutor
at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:97)
at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:48)
at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:107)
at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:71)
```
This is what user get after the fix:
``` …
```
=> Do not throw Exceptions in static initializer

core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java
Steps to reproduce:
Invoke a request without setting the access object inside the thread
object.
Proposed solution:
Throw a OS4J RuntimeException with a message.
Author: Sajid Nasir
Date: 10/13/2015
Affected files:
BaseOpenStackService.java
=> NPE thrown when building a request from OSClientSession object not existing inside the thread context (Fixes #458)

core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneTests.java, core-test/src/main/resources/identity.v3/authv3_domainId_userId.json, core-test/src/main/resources/identity.v3/authv3_domainId_userName.json, core-test/src/main/resources/identity.v3/authv3_domainName_userId.json, core-test/src/main/resources/identity.v3/authv3_unscoped.json, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/AccessWrapper.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneGroup.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneProject.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneRole.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneService.java, core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneUser.java, core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java
This PR related to issue Domain scoped authentication #497 and enables OpenStack4j to authenticate with a domain scope in the identity v3 case.
This is the last commit for this kind of issues which is compatible to the v2 implementation.
=> domain scoped authentication with tests

README.md, core-test/src/main/java/org/openstack4j/api/identity/KeystoneAuthenticationTests.java, core-test/src/main/java/org/openstack4j/api/identity/KeystoneProjectServiceTests.java, core-test/src/main/java/org/openstack4j/api/identity/KeystoneRoleServiceTests.java, core-test/src/main/java/org/openstack4j/api/identity/KeystoneUserServiceTests.java, core-test/src/main/resources/identity/roles_grantRole_error.json, core-test/src/main/resources/identity/roles_revokeRole_error.json, core/src/main/java/org/openstack4j/api/identity/RoleService.java, core/src/main/java/org/openstack4j/api/identity/UserService.java, core/src/main/java/org/openstack4j/core/transport/functions/ResponseToActionResponse.java, core/src/main/java/org/openstack4j/openstack/identity/internal/ProjectServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/RoleServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/UserServiceImpl.java
Moved the grant/revoke/check-user-role for domain and project context from the userService to the roleService. That would follow the v2-pattern of where this kind of calls should live.
Any comments by @gondor, @dhague ?
=> moved grant/revoke/check-role from user- to role-service

core/src/main/java/org/openstack4j/openstack/compute/domain/NovaFault.java
When `Server` is printed, this is a helpful piece of information.
=> Introduce NovaFault#toString

.gitignore
Intellij uses .iml files to store information of modules.
It would be good to ignore them to stop Intellij warning about .iml files not under version control.
=> Ignore .iml files

.travis.yml
See https://github.com/travis-ci/travis-ci/issues/5227 for more
information.
This patch should fix the Travis CI errors with OpenJDK.
=> Workaround for buffer overflow with OpenJDK in Travis CI

core/src/main/java/org/openstack4j/openstack/compute/domain/NovaBlockDeviceMappingCreate.java
This PR solves #567. The root cause is that OpenStack check boot_index == 0:
```
if not (image_uuid_specified and boot_index == 0):
raise exception.InvalidBDMFormat(
details=_("Mapping image to local is not supported."))
```
https://github.com/openstack/nova/commit/cadbcc440a2fcfb8532f38111999a06557fbafc2#diff-16c3690d30123cdcd3a1dca53021513aR201
=> convert boot_index to integer in JSON

core/pom.xml
Fixed unresolved constraint issue when bundling openstack4j in OSGi environment by embedding jackson-dataformat-yaml as a non-OSGi jar dependency.
=> Embeded jackson-dataformat-yaml as a non-OSGi jar dependency

core/src/main/java/org/openstack4j/model/network/builder/SubnetBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnet.java
Using noGateway method will build a slightly different NeutronSubnet, the only one difference is the property gateway_ip annotated with @JsonInclude to force serialization also if the value is null.
This change will let you add a subnet with gateway disabled.
=> Added noGateway method to the subnet builder

core/src/main/java/org/openstack4j/openstack/compute/internal/ServerServiceImpl.java
In case of http call with response, the returned entity should be consumed in order to release the resources associated with the call, and especially the http connection.
I am not sure where is the right place to consume and release the entity. I made a fix for my use-case - create snapshot, but most probably the this fix is applicable for more situations.
=> A fix regarding connection leak problem #579

core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneTokenServiceSpec.groovy, core-integration-test/src/test/resources/tapes/tokenService_crud_tape.yaml, core/src/main/java/org/openstack4j/api/identity/IdentityService.java, core/src/main/java/org/openstack4j/api/identity/TokenService.java, core/src/main/java/org/openstack4j/core/transport/ClientConstants.java, core/src/main/java/org/openstack4j/openstack/identity/internal/IdentityServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/TokenServiceImpl.java, core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
This addresses #540 and brings the missing token- check(), validate() and revoke() methods.
Note: This PR introduces the last service for the identity v3 part. The next PR should be the final before one before the release which will focus on the v2/v3 compatibility.
What do you think @gondor and @dhague ?
=> identity v3 token service

core-test/src/main/java/org/openstack4j/api/compute/ExtensionTests.java, core-test/src/main/resources/compute/extensions.json, core/src/main/java/org/openstack4j/openstack/common/ExtensionValue.java, core/src/main/java/org/openstack4j/openstack/compute/internal/ComputeServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/IdentityServiceImpl.java, core/src/main/java/org/openstack4j/openstack/manila/internal/ShareServiceImpl.java
Openstack4j currently has three extension list types:
Extensions, NovaExtensions and ManilaExtensions. This patch
consolidates those types into two different types, which should cover
all types used by different Openstack projects: ExtensionList and
Extensions.
This resolves #612
=> Unify extension list types

core-test/src/main/java/org/openstack4j/api/compute/ExtensionTests.java, core-test/src/main/resources/compute/extensions.json, core/src/main/java/org/openstack4j/openstack/common/ExtensionValue.java, core/src/main/java/org/openstack4j/openstack/compute/internal/ComputeServiceImpl.java, core/src/main/java/org/openstack4j/openstack/manila/internal/ShareServiceImpl.java
Openstack4j currently has three extension list types:
Extensions, NovaExtensions and ManilaExtensions. This patch
consolidates those types into two different types, which should cover
all types used by different Openstack projects: ExtensionList and
Extensions.
This resolves #612
This is a rebased version of #613 targeted for the v3_collaboration branch
=> Unify extension list types for v3

core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneGroupServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneProjectServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/KeystoneUserServiceSpec.groovy, core-integration-test/src/test/resources/tapes/groupService_group_crud_tape.yaml, core-integration-test/src/test/resources/tapes/userService_user_crud_tape.yaml, core-test/src/main/java/org/openstack4j/api/identity/KeystoneGroupServiceTests.java, core-test/src/main/java/org/openstack4j/api/identity/KeystoneProjectServiceTests.java, core-test/src/main/java/org/openstack4j/api/identity/KeystoneUserServiceTests.java, core-test/src/main/resources/identity/groups_getByName_empty.json, core-test/src/main/resources/identity/projects_getByName_empty.json, core-test/src/main/resources/identity/user_get_byName_byDomainId_not_exist.json, core/src/main/java/org/openstack4j/api/identity/GroupService.java, core/src/main/java/org/openstack4j/api/identity/ProjectService.java, core/src/main/java/org/openstack4j/api/identity/UserService.java, core/src/main/java/org/openstack4j/openstack/common/ListResult.java, core/src/main/java/org/openstack4j/openstack/identity/internal/GroupServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/ProjectServiceImpl.java, core/src/main/java/org/openstack4j/openstack/identity/internal/UserServiceImpl.java
Added Test Cases for failing getByName in 
org.openstack4j.openstack.identity.internal.GroupServiceImpl.getByName(String, String)
org.openstack4j.openstack.identity.internal.ProjectServiceImpl.getByName(String, String)
org.openstack4j.openstack.identity.internal.UserServiceImpl.getByName(String, String)
And fixed the problem by adding a first() method in ListResult<T> and calling it from the respective implementations.
Let me know what you think.
=> Fixed #625 getByName failing when result list is empty 

core/src/main/java/org/openstack4j/openstack/heat/utils/Environment.java
Hi,
Since Liberty, in the resource_registry we can use OS::Heat::None for disable or enables easily certain resources (http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::None).
I change the code, when this special entry is present, it doesn't try to load a content file and continue.
I made some tests in my use case and it seems to be good.
Bests regards.
Frédéric.
=> Add managing OS::Heat::None

connectors/http-connector/src/main/java/org/openstack4j/connectors/http/HttpResponseImpl.java
Fixes https://github.com/gondor/openstack4j/issues/635.
It seems that similar fix was already done in `HttpResponseImpl#header(String)` in unrelated change.
=> Fix #635: Do not propagate null response header from http-connector

core/src/main/java/org/openstack4j/api/compute/FlavorService.java, core/src/main/java/org/openstack4j/model/compute/Flavor.java, core/src/main/java/org/openstack4j/model/compute/builder/FlavorBuilder.java, core/src/main/java/org/openstack4j/openstack/common/DLPayloadEntity.java, core/src/main/java/org/openstack4j/openstack/compute/domain/NovaFlavor.java, core/src/main/java/org/openstack4j/openstack/compute/internal/FlavorServiceImpl.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Creating flavor omits json with extra null fields
=> Flavor issue

connectors/http-connector/pom.xml, connectors/jersey2/pom.xml, core-integration-test/src/test/groovy/org/openstack4j/api/AbstractSpec.groovy, distribution/pom.xml, pom.xml
- Project depends on 1.7
- Controllers affected by [JDK-7157360](https://bugs.openjdk.java.net/browse/JDK-7157360) depends on 1.8
- `distribution` module depends on `openstack4j-resteasy`
=> Fix #673: Bring back Java 7 support

core/src/main/java/org/openstack4j/openstack/heat/utils/Template.java, core/src/main/java/org/openstack4j/openstack/heat/utils/TemplateUtils.java
Hi,
If you use nested template and you have a mixed in the type property of a resource of relative path, absolute path, Http URL, Https URL, the loading of the nested templates failed because the path isn't correct.
I push a new method to calculate when the baseurl is needed or not to get the correct path to the file.
Cheers,
Frédéric
=> best reading nested template

core-integration-test/src/test/groovy/org/openstack4j/api/AbstractSpec.groovy
This fixes a mistake made in https://github.com/ContainX/openstack4j/pull/693.
=> Fixup 87237fa61a3982f41a12742f5ad15e7a6dc0efc5

core-test/src/main/java/org/openstack4j/openstack/internal/MicroVersionedServiceTest.java, core/src/main/java/org/openstack4j/api/manila/SharesService.java, core/src/main/java/org/openstack4j/openstack/internal/MicroVersion.java, core/src/main/java/org/openstack4j/openstack/internal/MicroVersionedOpenStackService.java, core/src/main/java/org/openstack4j/openstack/manila/internal/BaseShareServices.java, core/src/main/java/org/openstack4j/openstack/manila/internal/SharesServiceImpl.java, core/src/test/java/org/openstack4j/test/common/MicroVersionTest.java
Many OpenStack Services, like nova and manila, use micro-versions for their APIs.
This PR introduces a new base class for micro-versioned services, which will send an HTTP header specifying the desired micro-version with each API request.
Omitting this HTTP header causes the API to fall back to its minimum version (e.g. 2.1 for nova, 2.0 for manila), which prevents OpenStack4j to use newer API features.
This PR also includes a patch which enables micro-versions for manila. The latest version supported in this patch is 2.6, which equals the latest micro-version supported in Liberty. I will continue to work on supporting newer API versions (the latest micro-version for manila is 2.15 at the moment).
Please note that I consider this PR as a basis for discussion and that I am open for …
=> Introduce base for micro versions

core/src/main/java/org/openstack4j/openstack/manila/internal/SchedulerStatsServiceImpl.java
This patch resolves #719 for the maintenance branch
=> Fix URL for manila back-end storage pools in maintenance

core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneProjectServiceTests.java, core-test/src/main/resources/identity/v3/projects_create_response.json, core-test/src/main/resources/identity/v3/projects_update_response.json, core/src/main/java/org/openstack4j/model/identity/v3/Project.java, core/src/main/java/org/openstack4j/model/identity/v3/builder/ProjectBuilder.java, core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneProject.java
This includes the fix for #734 "add extra field on project
To support extra field, I have modified org.openstack4j.openstack.identity.v3.domain.KeystoneProject like followings.
* Put ```
private Map<String, String> extra = new HashMap<String, String>();``` in the KeystoneProject
* Create getExtra / setExtra with ```@JsonAnyGetter``` and ```@JsonAnySetter``` which are called when there are no explicitly mapped field.
* Ignore __is_domain__ field in setExtra which is automatically calculated field from keystone. Currently openstack4j just ignores this field. However with this patch if we don't ignore this in setExtra, it will be re-sent to the keystone during project update call and keystone will keep this in DB's extra fields.
* Put @JsonIgnore on getLinks(), because if it's re-sent to …
=> Fix #734: add extra field on project

core-integration-test/README.md, core-integration-test/pom.xml, core-integration-test/src/test/groovy/org/openstack4j/api/AbstractSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneAuthenticationSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneCredentialServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneDomainServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneGroupServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystonePolicyServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneProjectServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneRegionServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneRoleServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneServiceEndpointServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneTokenServiceSpec.groovy, core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneUserServiceSpec.groovy
*Finally* this fixes the bug in the it-module caused by different sorting of query paramteres in jdk1.7 and jdk1.8 by
- upgrading betamax to latest snapshot version
- use method, path, query params to match recordings in the tapes 
other:
- slightly updated the readme in integration-test module
- re-enable logging by adding missing dependency
@ContainX/openstack4j
=> Fix integrationtests

core-test/src/main/java/org/openstack4j/api/network/ListenerV2Tests.java, core-test/src/main/java/org/openstack4j/api/network/LoadBalancerV2Tests.java, core-test/src/main/resources/network/listenerv2.json, core-test/src/main/resources/network/listenerv2_update.json, core/src/main/java/org/openstack4j/model/network/ext/LbOperatingStatus.java, core/src/main/java/org/openstack4j/model/network/ext/LbProvisioningStatus.java, core/src/main/java/org/openstack4j/model/network/ext/ListenerV2.java, core/src/main/java/org/openstack4j/model/network/ext/ListenerV2Update.java, core/src/main/java/org/openstack4j/model/network/ext/LoadBalancerV2.java, core/src/main/java/org/openstack4j/model/network/ext/builder/ListenerV2Builder.java, core/src/main/java/org/openstack4j/model/network/ext/builder/ListenerV2UpdateBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronListenerV2.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronListenerV2Update.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronLoadBalancerV2.java
I was missing vipPortId in the loadbalancer object, and the tls and sni container refs in the listener object. In my openstack liberty you can only update the defaultTlsContainerRef, so that's how I've implemented here.
@vinodborole @gondor please take a look. Thanks!
=> adding vipPortId to loadbalancer, adding container refs to listener

core-test/src/main/java/org/openstack4j/api/network/ListenerV2Tests.java, core/src/main/java/org/openstack4j/model/network/ext/ListenerProtocol.java, core/src/main/java/org/openstack4j/model/network/ext/ListenerV2.java, core/src/main/java/org/openstack4j/model/network/ext/builder/ListenerV2Builder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronListenerV2.java
Missing terminated_https option for listener protocol. 
@vinodborole what have you found to be the most reliable source of documentation in general for OpenStack? Struggling to figure out which is most up to date/gets maintained.
=> adding terminated_https to listener protocol

core/src/main/java/org/openstack4j/api/telemetry/SampleService.java, core/src/main/java/org/openstack4j/openstack/telemetry/internal/SampleServiceImpl.java
The newly implemented ceilometer sample api (https://github.com/ContainX/openstack4j/pull/748) did not come with the query capabilities (https://github.com/ContainX/openstack4j/issues/154). This minor patch should fix that.
=> Add query capabilities to new ceilometer sample

core-test/src/main/java/org/openstack4j/api/storage/SchedulerStatsGetPoolTests.java, core-test/src/main/resources/storage/v2/cinder_scheduler-stats.json, core-test/src/main/resources/storage/v2/cinder_scheduler-stats_detail.json, core/src/main/java/org/openstack4j/api/storage/BlockStorageService.java, core/src/main/java/org/openstack4j/api/storage/SchedulerStatsGetPoolService.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderBackendStoragePool.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/VolumeBackendPool.java, core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockStorageServiceImpl.java, core/src/main/java/org/openstack4j/openstack/storage/block/internal/SchedulerStatsGetPoolServiceImpl.java
#762 
Author: chenguofeng
Email：gf.chen40@gmail.com
Add support of the following RESTful API:
GET/v2/​{tenant_id}​/scheduler-stats/get_pools
GET/v2/​{tenant_id}​/scheduler-stats/get_pools?detail=True
=> Add cinder get_pools interface for getting volume backend storage info

core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java
For unscoped token, if user have no default project/tenant, when authenticate, no service catalog is returned. Then for identity service just directly return the endpoint, not try get from catalog.
Also make changes to identity endpoint when there is both v2 and v3 available. So even if the catalog returned only contains v2 api endpoint, v3 api will still work. (In case some deployment both v2 and v3 is used.)
=> fix endpoint for identity service when no default tenant/project is available.

core-test/src/main/java/org/openstack4j/api/tacker/v1/TackerVimTests.java, core/src/main/java/org/openstack4j/core/transport/functions/ParseActionResponseFromJsonMap.java, core/src/main/java/org/openstack4j/openstack/tacker/domain/VnfAttributes.java, core/src/main/java/org/openstack4j/openstack/tacker/internal/VimServiceImpl.java, core/src/main/java/org/openstack4j/openstack/tacker/internal/VnfServiceImpl.java, core/src/main/java/org/openstack4j/openstack/tacker/internal/VnfdServiceImpl.java
* Added missing `Tacker Vnf` `static create()` method for setting `Vnf Attributes`..
* This can then be set in `VnfBuilder attributes(VnfAttributes attributes);`
* `TackerError` is now propagated..
* Currently `propagating` for `register - vim`, `create - vnf` and `create vnfd` calls on status `500`..
* Currently there is no way to propagate `404` status as well.. **Can this be enhanced**?
* `create` method (with param `PropagateOnStatus`) only propagates on the provided `status code`..
=> Added Tacker Vnf - Attributes  & TackerError Propagation..

core/src/main/java/org/openstack4j/core/transport/ClientConstants.java, core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java, core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java, core/src/main/java/org/openstack4j/openstack/internal/OSClientSession.java
=> Whaon patch issue 802

connectors/httpclient/src/main/java/org/openstack4j/connectors/httpclient/HttpResponseImpl.java
=> Fix #825 - NullPointerException in HttpClient connector

core/src/main/java/org/openstack4j/openstack/compute/domain/NovaFlavor.java
fix NovaFlavor , add @JsonIgnore to Boolean isPublic()  
issues : #818
=> fix NovaFlavor , add @JsonIgnore to Boolean isPublic()

CONTRIBUTING.md, README.md, connectors/httpclient/pom.xml, connectors/jersey2/pom.xml, connectors/okhttp/pom.xml, connectors/pom.xml, connectors/resteasy/pom.xml, core-integration-test/pom.xml, core-test/pom.xml, core/pom.xml, distribution/pom.xml, pom.xml
Fixes some URLs.
And the waffle graph will work again!
[![Throughput Graph](https://graphs.waffle.io/ContainX/openstack4j/throughput.svg)](https://waffle.io/ContainX/openstack4j/metrics)
=> Update links: gondor -> ContainX

core/src/main/java/org/openstack4j/model/network/ext/Firewall.java, core/src/main/java/org/openstack4j/model/network/ext/builder/FirewallBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewall.java
This PR fixes #857.
It adds support for router_ids in the Firewall class.
This was introduced in Kilo with the following commit:
https://github.com/openstack/neutron-fwaas/commit/d0704f056021b235caba1f906b1733f422ce68c1
=> Fix #857 - router_ids is missing from NeutronFirewall

core-test/src/main/java/org/openstack4j/api/compute/FlavorTests.java, core-test/src/main/resources/compute/flavors_detailed.json, core/src/main/java/org/openstack4j/api/compute/FlavorService.java, core/src/main/java/org/openstack4j/openstack/compute/internal/FlavorServiceImpl.java
=> add filteringParams on flavor list method

core/src/main/java/org/openstack4j/model/compute/Keypair.java, core/src/main/java/org/openstack4j/openstack/compute/domain/NovaKeypair.java
=> fix issue:869

core/src/main/java/org/openstack4j/openstack/compute/domain/NovaInterfaceAttachment.java
http://developer.openstack.org/api-ref-compute-v2.1.html
`"ip_address": "192.168.1.3",
"**subnet_id**": "f8a6e8f8-c2ec-497c-9f23-da9616de54ef"`
class org.openstack4j.openstack.compute.domain.NovaInterfaceAttachment.NovaFixedIp
=> fix json mapping for subnetId

pom.xml
Added `maven-enforcer-plugin` to master `pom.xml` to require Maven version 3.0+ or fail build with message: `Build FAILURE: Maven version 3.0+ REQUIRED!`
=> Issue #890 - Enforce build requirement of Maven version 3.0+

connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpResponseImpl.java
=> Implement close method in the okhttp HttpResponseImpl to avoid leak

core-test/src/main/java/org/openstack4j/api/storage/VolumeBackupTests.java, core-test/src/main/resources/storage/v1/volumebackup_from_snapshot.json, core/src/main/java/org/openstack4j/model/storage/block/VolumeBackup.java, core/src/main/java/org/openstack4j/model/storage/block/VolumeBackupCreate.java, core/src/main/java/org/openstack4j/model/storage/block/builder/VolumeBackupCreateBuilder.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeBackup.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeBackupCreate.java
Create a volume backup from a snapshot.
This feature is not documented in 
http://developer.openstack.org/api-ref/block-storage/v3/?expanded=create-a-backup-detail
but it is indeed supported by the Openstack server and the CLI
https://github.com/ContainX/openstack4j/issues/874
=> support snapshot_id in volume backups

core/src/main/java/org/openstack4j/model/network/Port.java, core/src/main/java/org/openstack4j/model/network/builder/PortBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPortCreate.java
=> Kept the portsecurityenabled property as undefined

core/src/main/java/org/openstack4j/core/transport/Config.java, core/src/test/java/org/openstack4j/test/core/transport/ConfigTest.java
=> Bug #913: add SSLContext and HostnameVerifier to hashCode and equals

core-test/src/main/java/org/openstack4j/api/image/v2/ImageV2Tests.java, core/src/main/java/org/openstack4j/model/image/v2/Image.java, core/src/main/java/org/openstack4j/model/image/v2/Task.java, core/src/main/java/org/openstack4j/model/image/v2/builder/ImageBuilder.java, core/src/main/java/org/openstack4j/openstack/compute/domain/NovaServer.java, core/src/main/java/org/openstack4j/openstack/image/v2/domain/GlanceImage.java, core/src/main/java/org/openstack4j/openstack/image/v2/domain/GlanceTask.java
=> use Long insead of Integer in class GlanceImage

core-test/src/main/java/org/openstack4j/api/compute/ServerTests.java, core-test/src/main/resources/compute/server_evacuate.json, core/src/main/java/org/openstack4j/api/compute/ServerService.java, core/src/main/java/org/openstack4j/model/compute/actions/EvacuateOptions.java, core/src/main/java/org/openstack4j/openstack/compute/domain/AdminPass.java, core/src/main/java/org/openstack4j/openstack/compute/domain/actions/EvacuateAction.java, core/src/main/java/org/openstack4j/openstack/compute/internal/ServerServiceImpl.java
Hi, I'm taemin
I added Evacuate Server.
I did tests about this api and checked the result.
The example below.
ServerPassword password =
os.compute().servers().evacuate("1427b0a6-e6a1-496",
EvacuateOptions.create().host("compute1").onSharedStorage(false));	
System.out.println(password.getPassword());
I hope you review codes I pulled.
=> add Evacuate Server (evacuate Action)

core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java
Releated these issues
https://github.com/ContainX/openstack4j/issues/920
https://github.com/ContainX/openstack4j/issues/901
=> add missed 'os-vol-host-attr:host' property on CinderVolume

core-test/src/main/java/org/openstack4j/api/storage/ObjectStorageTests.java, core/src/main/java/org/openstack4j/openstack/storage/object/functions/ParseObjectFunction.java
This PR resolves issue #944  by modifying ParseObjectFunction such that we now get the eTag for objects retrieved from swift.  Also added a unit test.
=> Issue 944: etag support in os.objectStorage().objects().get()

Dockerfile, Makefile
This PR resolves Issue #957 in which one of the unit tests fails because it has root privileges in docker.  With this patch maven runs in docker as a non-root user named "builder" instead.
=> issue 957: run as non-root user in docker

core/src/main/java/org/openstack4j/model/network/options/PortListOptions.java
"name" should be specified instead of "display_name".
Link to the issue: https://github.com/ContainX/openstack4j/issues/963
=> Fixing port name list option.

core/src/main/java/org/openstack4j/model/network/Port.java, core/src/main/java/org/openstack4j/model/network/builder/PortBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPortCreate.java, core/src/main/java/org/openstack4j/openstack/networking/internal/PortServiceImpl.java
Adding binding extension data to neutron port
Link to an issue: https://github.com/ContainX/openstack4j/issues/966
=> Adding neutron port binding data support.

core/src/main/java/org/openstack4j/openstack/image/domain/functions/ImageForUpdateToHeaders.java
Currently if you set Id with ImageBuilder it will get ignored. This
prevents user passing custom image UUID for newly create image.
=> Allow set ID when creating image

core-test/src/main/java/org/openstack4j/api/network/SubnetTests.java, core-test/src/main/resources/network/subnet_ipv6.json, core/src/main/java/org/openstack4j/model/network/Ipv6AddressMode.java, core/src/main/java/org/openstack4j/model/network/Ipv6RaMode.java, core/src/main/java/org/openstack4j/model/network/Subnet.java, core/src/main/java/org/openstack4j/model/network/builder/SubnetBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnet.java
Hi @auhlig 
I couldn't find subnet ipv6 properties in the lastest snapshot.
I don't know what is wrong.
Could you check it again?
Once, I created PR again. 
ipv6_address_mode
: The IPv6 address modes specifies mechanisms for assigning IP
addresses. Value is slaac, dhcpv6-stateful, dhcpv6-stateless or null.
ipv6_ra_mode
: The IPv6 router advertisement specifies whether the networking service
should transmit ICMPv6 packets, for a subnet. Value is slaac,
dhcpv6-stateful, dhcpv6-stateless or null.
=> support ipv6 properties in subnet again

core/src/main/java/org/openstack4j/api/networking/SecurityGroupRuleService.java, core/src/main/java/org/openstack4j/api/networking/SecurityGroupService.java, core/src/main/java/org/openstack4j/openstack/networking/internal/SecurityGroupRuleServiceImpl.java, core/src/main/java/org/openstack4j/openstack/networking/internal/SecurityGroupServiceImpl.java
releated https://github.com/ContainX/openstack4j/issues/974
=> add security group and rules filterable list method

core-test/src/main/java/org/openstack4j/api/image/v2/ImageV2Tests.java, core-test/src/main/resources/image/v2/image.json, core/src/main/java/org/openstack4j/model/image/v2/Image.java, core/src/main/java/org/openstack4j/model/image/v2/builder/ImageBuilder.java, core/src/main/java/org/openstack4j/openstack/image/v2/domain/GlanceImage.java
Currently, there is no way to passing additional properties (e.g. hw_vif_model, hw_disk_bus) when creating image through Glance V2
https://developer.openstack.org/api-ref/image/v2/index.html?expanded=create-an-image-detail#create-an-image
=> Allow passing additional properties for Glance V2

core/src/main/java/org/openstack4j/api/senlin/SenlinNodeService.java, core/src/main/java/org/openstack4j/openstack/senlin/internal/SenlinNodeServiceImpl.java
A new method in `SenlinNodeService` allows to obtain details (via `Node.getDetails()`) about physical object that backs the cluster node correctly. This can be done using `show_details` query parameter. See details about this parameter [here](https://developer.openstack.org/api-ref/clustering/?expanded=show-node-details-detail)
=> SenlinNodeService: details about physical object that backs the node

README.md, core-test/src/main/java/org/openstack4j/api/identity/v3/KeystoneTokenlessTest.java, core/src/main/java/org/openstack4j/api/OSClient.java, core/src/main/java/org/openstack4j/core/transport/ClientConstants.java, core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java, core/src/main/java/org/openstack4j/openstack/common/Auth.java, core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneAuth.java, core/src/main/java/org/openstack4j/openstack/internal/BaseOpenStackService.java, core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java, core/src/main/java/org/openstack4j/openstack/internal/OSClientSession.java
Currently, keystone supports client certificate without having to issue a
token, so it is necessary to add http headers to support this feature.
=> Add http headers for supporting keystone tokenless

core-test/src/main/java/org/openstack4j/api/network/NetworkTests.java, core-test/src/main/resources/network/network_zone.json, core/src/main/java/org/openstack4j/model/network/Network.java, core/src/main/java/org/openstack4j/model/network/builder/NetworkBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronNetwork.java
Hi, I Added two perperties for availability zone for the network.
-  availability_zone_hints : The availability zone candidate for the network. (create and read)
-  availability_zones : 	The availability zone for the network. (read only)
* these properties is for Mitaka or above.
=> Add additional properties of the availability zone hint for the network.

core-test/src/main/java/org/openstack4j/api/workflow/ActionDefinitionTest.java, core-test/src/main/java/org/openstack4j/api/workflow/WorkbookDefinitionTest.java, core-test/src/main/java/org/openstack4j/api/workflow/WorkflowDefinitionTest.java, core-test/src/main/java/org/openstack4j/api/workflow/WorkflowExecutionTest.java, core-test/src/main/resources/workflow/new_wf_exec.json, core-test/src/main/resources/workflow/wf_exec.json, core-test/src/main/resources/workflow/wf_exec_create.json, core-test/src/main/resources/workflow/wf_execs.json, core/src/main/java/org/openstack4j/api/workflow/WorkflowExecutionService.java, core/src/main/java/org/openstack4j/core/transport/HttpEntityHandler.java, core/src/main/java/org/openstack4j/model/common/ActionResponse.java, core/src/main/java/org/openstack4j/model/workflow/ActionExecution.java, core/src/main/java/org/openstack4j/model/workflow/Execution.java, core/src/main/java/org/openstack4j/model/workflow/TaskExecution.java, core/src/main/java/org/openstack4j/model/workflow/WorkflowExecution.java, core/src/main/java/org/openstack4j/model/workflow/builder/ExecutionBuilder.java, core/src/main/java/org/openstack4j/model/workflow/builder/WorkflowBuilders.java, core/src/main/java/org/openstack4j/model/workflow/builder/WorkflowExecutionBuilder.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java, core/src/main/java/org/openstack4j/openstack/workflow/builder/MistralBuilders.java, core/src/main/java/org/openstack4j/openstack/workflow/domain/BaseExecution.java, core/src/main/java/org/openstack4j/openstack/workflow/domain/MistralWorkflowExecution.java, core/src/main/java/org/openstack4j/openstack/workflow/internal/WorkflowExecutionServiceImpl.java
* Made ActionResponse able to various 2xx HTTP codes, not only 200
** Added one more static method ActionResponse.actionSuccess() taking
an integer code
** Fixed deletion tests for workflow, workbook and actions definitions
to expect 204 code. 200 was expected due to aforementioned limitation
* Added an endpoint for Mistral workflow executions
=> Mistral: adding workflow executions endpoint

.gitignore, core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java, core-test/src/main/resources/storage/v2/volume.json, core/src/main/java/org/openstack4j/model/storage/block/Volume.java, core/src/main/java/org/openstack4j/model/storage/block/VolumeSnapshot.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java
Fixes #1019. For v2/v3, getName() and getDescription() should return the correct values. For v1, it will return null as API fields since v2 are updated to `name` and `description`.
=> Renamed CinderVolume properties to be compatible with block storage API v2, fixed broken VolumeTests

core-test/src/main/java/org/openstack4j/openstack/common/TelemetryDateDeserializerTest.java, core/src/main/java/org/openstack4j/model/telemetry/SampleCriteria.java, core/src/main/java/org/openstack4j/model/telemetry/Statistics.java, core/src/main/java/org/openstack4j/openstack/common/TelemetryDateDeserializer.java, core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerStatistics.java, core/src/main/java/org/openstack4j/openstack/telemetry/internal/MeterServiceImpl.java
Hi,
This is my first PR for openstack4j. The dates being parsed for the Statistics are not offset anymore by the microseconds as explained in #928. I am having problems running the core-tests though, each time, I am getting `Tests are skipped.` even when adding `-Dmaven.test.skip=false`
If someone could give me a hand that would be great
=> 928 ceilometer statistics date parsing

core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java
Original fix in #1046 introduced a bug with V1 volume creation where new volume would result with no name or description. This is a NO-IMPACT fix to set extra fields which will be ignored for cinder API V2/V3.
=> Update builder to set old deprecated fields to support volume creation (preserving name and description) for cinder API V1

core-test/src/main/java/org/openstack4j/api/compute/ServerTests.java, core/src/main/java/org/openstack4j/api/compute/ServerService.java, core/src/main/java/org/openstack4j/openstack/compute/domain/actions/CreateSnapshotAction.java, core/src/main/java/org/openstack4j/openstack/compute/internal/ServerServiceImpl.java
Openstack API to [create image](https://developer.openstack.org/api-ref/compute/?expanded=create-image-createimage-action-detail#create-image-createimage-action) allows passing optional metadata properties. Overloaded `createSnapshot()` to handle additional metadata and maintain backwards compatibility.
=> Added a new method createSnapshot() to invoke create image action API with metadata properties

core/src/main/java/org/openstack4j/model/storage/object/SwiftHeaders.java
I was getting NULL out of the `getETag` method (using 3.0.3 with httpclient, targeting Rackspace). Per the [Swift API docs](https://developer.openstack.org/api-ref/object-storage/?expanded=get-object-content-and-metadata-detail), the header is `Etag`, not `ETag`, and I've confirmed with a custom build of OpenStack4J that this case change fixes the issue for me.
I believe this would resolve #994
=> Fix ETag header to match documented name: 'Etag'

core-test/src/main/java/org/openstack4j/api/AbstractTest.java, core-test/src/main/java/org/openstack4j/api/sahara/ClusterTests.java, core-test/src/main/resources/identity/v2/access.json, core-test/src/main/resources/identity/v3/authv3_project.json, core-test/src/main/resources/sahara/cluster_create_req.json, core-test/src/main/resources/sahara/cluster_create_resp.json, core/src/main/java/org/openstack4j/model/sahara/ServiceConfig.java, core/src/main/java/org/openstack4j/model/sahara/builder/ServiceConfigBuilder.java, core/src/main/java/org/openstack4j/openstack/sahara/domain/SaharaServiceConfig.java
This PR allows values in ServiceConfig to be an integer or any other types than just a string. So the generated JSON is correctly formatted according to the type of value.
=> Allow value to be object type in ServiceConfig

core/src/main/java/org/openstack4j/openstack/identity/internal/DefaultEndpointURLResolver.java, core/src/main/java/org/openstack4j/openstack/identity/v3/functions/ServiceToServiceType.java
According to the in identity V2, the service is lookup by name or by type (see [ref](https://github.com/ContainX/openstack4j/blob/d9a6417f1c33c8901cec5f3fc7b3f6caa3458fd3/core/src/main/java/org/openstack4j/openstack/identity/v2/domain/KeystoneAccess.java#L237)). However, Identity V3 lookup only by type. This PR intends to bring back the ability to lookup service by name.
=> Allow identity V3 to lookup service by name

core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java, core-test/src/main/resources/storage/v2/createVolume-muitiattach.json, core/src/main/java/org/openstack4j/model/storage/block/Volume.java, core/src/main/java/org/openstack4j/model/storage/block/builder/VolumeBuilder.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java
Added multiattach property when creating volume.
multiattach (Optional) : To enable this volume to attach to more than
one server, set this value to true. Default is false.
=> Support multiattach property in volume

core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewallUpdate.java
fix  Firewall policy param cannot be updated #1068
=> fix  Firewall policy param cannot be updated

connectors/resteasy/pom.xml, connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/HttpCommand.java, connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/HttpExecutorServiceImpl.java, connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/HttpResponseImpl.java, connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/executors/ApacheHttpClientEngine.java, connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/executors/ApacheHttpClientExecutor.java
Description: 1. Updated Apache httpclient version and corresponding code for IPv6+ https issue.
2. Added support for IgnoreSSLVerification and custom SSLHostnameVerifier.
=> Issue : #[1070](https://github.com/ContainX/openstack4j/issues/1070)

README.md, connectors/http-connector/pom.xml, connectors/httpclient/pom.xml, connectors/jersey2/pom.xml, connectors/okhttp/pom.xml, connectors/pom.xml, connectors/resteasy/pom.xml, core-integration-test/it-httpclient/pom.xml, core-integration-test/it-jersey2/pom.xml, core-integration-test/it-okhttp/pom.xml, core-integration-test/it-resteasy/pom.xml, core-integration-test/pom.xml, core-test/pom.xml, core/pom.xml, distribution/pom.xml, pom.xml
I try to catch up with the pending PRs on the weekend. New release could be done next week.
=> 3.1.0 release

core/pom.xml, core/src/main/java/org/openstack4j/openstack/heat/utils/Environment.java, core/src/main/java/org/openstack4j/openstack/heat/utils/Template.java
While experimenting with updating jackson version I noticed, `com.fasterxml.jackson.dataformat.yaml.snakeyaml.*` is [no longer exposed](https://github.com/FasterXML/jackson-dataformat-yaml/commit/c69224917fd235732e51c8327f23af7f7038108f) so I am switching to proper dependency which should hopefully resolve the OSGi limitation as well.
=> Switch to standalone snakeyaml

core-test/src/main/java/org/openstack4j/api/barbican/SecretTests.java, core/src/main/java/org/openstack4j/model/barbican/Secret.java, core/src/main/java/org/openstack4j/model/barbican/builder/SecretCreateBuilder.java, core/src/main/java/org/openstack4j/openstack/barbican/domain/BarbicanSecret.java, core/src/main/java/org/openstack4j/openstack/barbican/internal/SecretServiceImpl.java
Some minor fixes to match the Barbican API.
=> fix(secret): fix wrong representation of Secret values & add payload

core/src/main/java/org/openstack4j/model/compute/Server.java
According to the OpenStack documentation there is a rescue status - https://developer.openstack.org/api-guide/compute/server_concepts.html
Thus I've added this status to Server.Status enum
=> add rescue server status

connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpExecutorServiceImpl.java
org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.execute(...) no longer returns null.
If it encounters an exception, it now throws.
Previously it suppressed the original exception and returned null, causing downstream code to fail with a NullPointerException.
See https://github.com/ContainX/openstack4j/issues/1094 for details.
=> [issue 1094] Fix NPEs caused by okhttp HttpExecutorServiceImpl

core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/SetBootableAction.java, core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
Implement the following endpoint as per the Block Storage API document https://developer.openstack.org/api-ref/block-storage/v3/
```POST /v3/{project_id}/volumes/{volume_id}/action```
Update a volume’s bootable status
project_id | path | string | The UUID of the project in a multi-tenancy cloud.
volume_id | path | string | The UUID of the volume.
os-set_bootable | body | object | The os-set_bootable action.
bootable | body | boolean | Enables or disables the bootable attribute. You can boot an instance from a bootable volume.
=> Update volume bootable status

core/src/main/java/org/openstack4j/api/storage/BlockVolumeService.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeAttachment.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/DetachAction.java, core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java
add detach method to blockstorage api
=> add detach method to blockstorage api

core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPortCreate.java
Adding device_owner and device_id Port attributes
support to the port create model entity
Link to an issue: https://github.com/ContainX/openstack4j/issues/1117
=> Adding device_owner and device_id support for Port

core-test/src/main/java/org/openstack4j/api/image/v2/ImageV2Tests.java, core-test/src/main/resources/image/v2/image-with-locations.json, core/src/main/java/org/openstack4j/model/image/v2/Image.java, core/src/main/java/org/openstack4j/openstack/image/v2/domain/GlanceImage.java
Seeing parsing error when image from Glance V2 contains "locations"
According to [Glance API V2](https://developer.openstack.org/api-ref/image/v2/#show-image-details):
> A list of objects, each of which describes an image location. Each object contains a url key, whose value is a URL specifying a location, and a metadata key, whose value is a dict of key:value pairs containing information appropriate to the use of whatever external store is indicated by the URL.
Add a new Location object, and replace the locations from List<String> to List<Location>
```{
"images": [{
"container_format": "bare",
"min_ram": 0,
"updated_at": "2017-10-05T07:37:07Z",
"file": "/v2/images/xxxx/file",
"owner": "xxxx",
"id": "xxxx",
"size": 10000,
"self": "/v2/images/xxxx",
"disk_format": "qcow2",
"direct_url": …
```
=> Fix parsing error when Glance V2 image contains optional locations

core/src/main/java/org/openstack4j/core/transport/functions/ParseActionResponseFromJsonMap.java
octavia error like this
{
"debuginfo": null,
"faultcode": "xxx",
"faultstring": "xxx"
}
"debuginfo" can be NULL
=> Add octavia error msg to ActionResponse

connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpCommand.java, connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpExecutorServiceImpl.java, core-integration-test/pom.xml
I have observed in production 2500ish openstack connections in `CLOSE_WAIT` state that took several minutes to get properly closed (by `ConnectionPool#cleanup()`). I turned out every interaction with openstack creates separate `OkHttpClient` instance which is discouraged so dedicated auto-cleaned connection pools have no chance to have any positive effect. I am not convinced it is wise to share the client/connectionpool for the `HttpExecutorServiceImpl` so I am settling with the eager resource cleanup.
I have retested this change via jenkinsci/openstack-cloud-plugin and the interaction that used to create 100+ connection that took a while to be released, this hardly ever create more than 5 at the same time.
=> Make sure the number of okhttp CLOSE_WAIT connections is always manageable

connectors/httpclient/src/main/java/org/openstack4j/connectors/httpclient/HttpExecutorServiceImpl.java
Moved the return method after the finally block thus guaranteeing that the initial connection is always closed before the recursive invocation.
=> Fix issue #1165.

connectors/resteasy/src/main/java/org/openstack4j/connectors/resteasy/executors/ApacheHttpClientEngine.java
The SSLContext of an HttpRequest was not passed to the HttpClientBuilder in the ApacheHttpClientEngine. This closes #1161.
=> Consider the SSLContext of an HttpRequest's Config object when using the Resteasy connector

core-test/src/main/java/org/openstack4j/api/heat/StackServiceTests.java, core-test/src/main/resources/heat/abandon.json, core-test/src/main/resources/heat/adopt.json, core/src/main/java/org/openstack4j/api/heat/StackService.java, core/src/main/java/org/openstack4j/model/heat/AdoptStackData.java, core/src/main/java/org/openstack4j/openstack/heat/domain/HeatAdoptStackData.java, core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackAdopt.java, core/src/main/java/org/openstack4j/openstack/heat/internal/StackServiceImpl.java
Implements issue #1135. 
There are 2 new methods in `heat.StackService`: abandon and adopt. New interface `AdoptStackData` describes `adopt_stack_data` element, used as an input for stack adoption and as a return value for stack abandoning.
Basic unit tests are included. The code was tested against real Openstack instance as well.
=> Heat service, adding support for stack abandon and adopt 

core-test/src/main/java/org/openstack4j/api/network/NetworkTests.java, core/src/main/java/org/openstack4j/api/networking/ext/AgentService.java, core/src/main/java/org/openstack4j/openstack/networking/internal/ext/AgentServiceImpl.java
I can't do attach test because the request return null and break test with resteasy provider
=> neutron attach and detach network to agent dhcp

core-test/src/main/resources/identity/v2/access.json, core-test/src/main/resources/identity/v3/authv3_project.json, core-test/src/main/resources/telemetry/alarm.json, core/src/main/java/org/openstack4j/openstack/identity/v3/internal/BaseIdentityServices.java, core/src/main/java/org/openstack4j/openstack/identity/v3/internal/IdentityServiceImpl.java
The code below fixes the github issue #1198: "Identity service not working with OS4j".
Keystone version v3 is missed in the keystone endpoint URL due to which the Identity service APIs fail with the error message "Resource could not be found (404)". The code appends version "/v3" to the keystone endpoint URL which fixes the issue.
Added a new class "BaseIdentityServices" to enforce keystone version to endpoint URL.
=> Solves the issue #1198: "Identity service not working with OS4j".

core/src/main/java/org/openstack4j/api/image/v2/ImageService.java, core/src/main/java/org/openstack4j/model/image/v2/CachedImage.java, core/src/main/java/org/openstack4j/openstack/image/v2/domain/CachedGlanceImage.java, core/src/main/java/org/openstack4j/openstack/image/v2/internal/ImageServiceImpl.java
This pull request implements the listCachedImages() API to list the cached images for Glance v2 images.
This API is available in glance v1 but is missing in v2 version. Hence implemented the same for V2.
=> Implement listCachedImages() for Glance V2 Images

.travis.yml
Cache the m2 directory so artifacts dont need to be downloaded multiple times.
https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)
=> Cache maven artifact directory to enable faster builds.
